### ISSUE TITLE
Smaller Dataset Implementation

### ISSUE THREAD

**Issue by JackSmith156403** [Onedean/MainTUL#1]
Is there any constant number of user is required to run this project? For foursquare_mini dataset, I have tried this project to run with 399 user instead of 400. It give some CUDA error. Could you please tell me how can I solve this one?

**Comment by Onedean** [comment]
> Is there any constant number of user is required to run this project? For foursquare_mini dataset, I have tried this project to run with 399 user instead of 400. It give some CUDA error. Could you please tell me how can I solve this one?

No, it depends on the number of users in the database. If you provide a detailed error log, I will take some time.

**Comment by JackSmith156403** [comment]
![image](https://user-images.githubusercontent.com/92089614/230153469-8bd2858a-a36f-4834-a2f3-9e6e1213c899.png)
![image](https://user-images.githubusercontent.com/92089614/230153624-cccaa5db-f8c1-4b03-b969-9080ec00e375.png)
I have taken the foursqure_mini dataset but with only 200 users. I have attached the screenshot. Could you please tell me what I am doing wrong? I will use this project in GeoLife Dataset.
@Onedean Thanks for your quick reply

**Comment by Onedean** [comment]
> ![image](https://user-images.githubusercontent.com/92089614/230153469-8bd2858a-a36f-4834-a2f3-9e6e1213c899.png) ![image](https://user-images.githubusercontent.com/92089614/230153624-cccaa5db-f8c1-4b03-b969-9080ec00e375.png) I have taken the foursqure_mini dataset but with only 200 users. I have attached the screenshot. Could you please tell me what I am doing wrong? I will use this project in GeoLife Dataset. @Onedean Thanks for your quick reply

It seems that the size of the vocabulary is out of bounds, so I suggest you check the operation of mapping the original data to the vocabulary. 😊

**Comment by Onedean** [comment]
It should be noted that only timestamp information doesn't need to be mapped to a vocabulary. Hope it can help you! @JackSmith156403
